### PR TITLE
Arduino interface readme and examples

### PR DESCRIPTION
**Pull request by kklis**

### CODE REVIEW

**Comment by kklis** [comment]
Thanks!

-----Wiadomość oryginalna-----
Od: "Mockba the Borg" <notifications@github.com>
Wysłano: ‎2016-‎07-‎28 17:06
Do: "MockbaTheBorg/CPMduino" <CPMduino@noreply.github.com>
DW: "Krzysztof Kliś" <krzysztof.klis@gmail.com>; "Author" <author@noreply.github.com>
Temat: Re: [MockbaTheBorg/CPMduino] Arduino interface readme and examples(#4)

Merged #4.

**Comment by MockbaTheBorg** [comment]
One quick question:

On the AnalogRead BDOS call, you change the contents of AF, however, F
contains the CPU flags, and overwriting the flags may be an issue.
Maybe you should return the value of the AnalogRead (is it 8 bits or 16
bits?) into A only (if it is 8 bits) or to maybe BC pair (if it is 16 bits).

Cheers,
Marcelo.

**Comment by kklis** [comment]
According to the specifications at https://www.arduino.cc/en/Reference/AnalogRead the returned value can be from 0 to 1023, so I need a register pair.
You are right about the AF, I will fix it.

**Comment by kklis** [comment]
https://github.com/MockbaTheBorg/CPMduino/pull/5

**Pull request merged**
